# Generated by Django 5.2.4 on 2025-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                    ("ARCHIVED", "Archived"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
