# Generated by Django 5.2.4 on 2025-08-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_attachment_file_attachment_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
    ]
