# Generated by Django 5.2.4 on 2025-09-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='isUploaded',
            field=models.BooleanField(default=False),
        ),
    ]
