# Generated by Django 5.2.4 on 2025-09-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_attachment_isuploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='isUploaded',
            new_name='is_uploaded',
        ),
    ]
