name: CI - Ruff & Django Tests (Compose)

on:
  pull_request:
    branches:
      - "**"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check .

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Show running containers
        run: docker compose ps

      - name: Wait for DB
        run: |
          echo "Waiting for database..."
          sleep 10  # если Postgres запускается быстро, можно меньше

      - name: Run Django tests (manage.py)
        run: docker compose exec -T -e DJANGO_SETTINGS_MODULE=config.settings_test web python manage.py test --verbosity 2

      - name: Show container logs
        if: failure()
        run: docker compose logs
